- hosts: front
  become: true
  roles:
    - playbooks/vuejs
    - playbooks/front-app
  environment:
    PORT: 8080[REVISAR PORQUE REACT CORRE EN EL 3000]
#    PORT: 3000

 # - hosts: back
#   become: true
#   roles:
#     - role: playbooks/back-app 